### ISSUE TITLE
rj11 female connector pin layout

### ISSUE THREAD

**Issue by malvo** [krauskopf/WifiEnergyMonitorFerraris8266#1]
i'm unable to find the color layout @ the rj11 female connector. could you provide an overview which pin is connected to which color? 

f.e. with pin 1 being on the left side front view and nibble down
![rj11](https://user-images.githubusercontent.com/10484851/150016915-04f16183-88f8-4378-9b99-e73298bfffc5.png)

**Comment by krauskopf** [comment]
Sorry for the delay @malvo . Was on a business trip the last days. Added some pics to the readme.md now.
